// ============================================================
// Industrial areas of India, keyed by state → district → areas.
//
// WHY THIS FILE IS THE VOLUME LEVER
//
// A Google text search returns at most 60 results per phrase. Searching a whole
// district therefore finds 60 companies whether the district holds 80 or 8,000.
// Each industrial estate is its own separate 60, so listing the estates inside a
// district is what turns a few hundred companies into a few thousand — and it
// aims the search where manufacturers physically are, rather than at the retail
// high street of the district town.
//
// THE RULES THIS LIST FOLLOWS
//
//   1. District keys MUST match supabase/seed-data/territory-seed.json exactly,
//      including the official spellings. A key that matches nothing is invisible
//      and silent — discovery-query.test.ts fails the build if one appears.
//   2. Every entry must be a place Google Maps can resolve. An estate name that
//      nobody has mapped returns zero and wastes a billable call.
//   3. A district with no distinct industrial cluster is simply left out. It is
//      then searched at district level, which is the correct fallback: fewer
//      results, never wrong ones. Omitting is safe; inventing is not.
//
// Names follow each state's industrial development corporation, because that is
// how the estates are signposted and therefore how Google has them: MIDC in
// Maharashtra, GIDC in Gujarat, SIPCOT/SIDCO in Tamil Nadu, UPSIDA in Uttar
// Pradesh, RIICO in Rajasthan, HSIIDC in Haryana, KIADB in Karnataka, TSIIC in
// Telangana, APIIC in Andhra Pradesh.
// ============================================================

export type AreasByDistrict = Record<string, string[]>;

export const INDUSTRIAL_AREAS: Record<string, AreasByDistrict> = {
  // ── West ──────────────────────────────────────────────────
  Maharashtra: {
    Pune: [
      "Bhosari MIDC",
      "Chakan MIDC",
      "Ranjangaon MIDC",
      "Pimpri Chinchwad",
      "Hinjawadi",
      "Kurkumbh MIDC",
      "Jejuri MIDC",
      "Talegaon MIDC",
      "Baramati MIDC",
      "Hadapsar Industrial Estate",
    ],
    Thane: [
      "Wagle Industrial Estate",
      "Dombivli MIDC",
      "Ambernath MIDC",
      "Badlapur MIDC",
      "Murbad MIDC",
      "Bhiwandi",
      "Kalyan",
    ],
    Raigad: [
      "Taloja MIDC",
      "Patalganga MIDC",
      "Rasayani",
      "Roha MIDC",
      "Mahad MIDC",
      "Khopoli",
      "Panvel",
      "Pen",
    ],
    Palghar: ["Tarapur MIDC", "Boisar", "Palghar MIDC", "Vasai", "Dahanu", "Wada"],
    Nashik: ["Satpur MIDC", "Ambad MIDC", "Sinnar MIDC", "Igatpuri", "Malegaon", "Dindori"],
    Aurangabad: ["Waluj MIDC", "Shendra MIDC", "Chikalthana MIDC", "Paithan MIDC", "Bidkin"],
    Jalna: ["Jalna MIDC", "Ambad Jalna", "Partur"],
    Nagpur: ["Butibori MIDC", "Hingna MIDC", "Kalmeshwar MIDC", "MIHAN Nagpur", "Kamptee"],
    Kolhapur: [
      "Shiroli MIDC",
      "Gokul Shirgaon MIDC",
      "Kagal MIDC",
      "Ichalkaranji",
      "Hatkanangale",
      "Jaysingpur",
    ],
    Sangli: ["Kupwad MIDC", "Miraj MIDC", "Vita MIDC", "Islampur"],
    Satara: ["Satara MIDC", "Shirwal MIDC", "Karad MIDC", "Phaltan MIDC", "Wai"],
    Solapur: ["Chincholi MIDC", "Akkalkot Road MIDC", "Barshi", "Pandharpur"],
    Ahmednagar: ["Ahmednagar MIDC", "Supa MIDC", "Sangamner", "Shrirampur"],
    "Mumbai Suburban": ["Andheri MIDC", "Marol Industrial Estate", "SEEPZ Andheri", "Jogeshwari"],
    Latur: ["Latur MIDC", "Ausa", "Udgir"],
    Nanded: ["Nanded MIDC", "Krishnur MIDC", "Dharmabad"],
    Amravati: ["Amravati MIDC", "Nandgaon Peth MIDC", "Achalpur"],
    Akola: ["Akola MIDC", "Akot", "Murtijapur"],
    Jalgaon: ["Jalgaon MIDC", "Bhusawal", "Chalisgaon", "Amalner"],
    Dhule: ["Dhule MIDC", "Shirpur", "Dondaicha"],
    Nandurbar: ["Nandurbar MIDC", "Shahada"],
    Chandrapur: ["Chandrapur MIDC", "Tadali MIDC", "Ballarpur", "Ghugus"],
    Wardha: ["Wardha MIDC", "Hinganghat", "Pulgaon"],
    Beed: ["Beed MIDC", "Majalgaon", "Parli"],
    Osmanabad: ["Osmanabad MIDC", "Tuljapur", "Naldurg"],
    Parbhani: ["Parbhani MIDC", "Jintur"],
    Hingoli: ["Hingoli MIDC", "Basmath"],
    Buldhana: ["Khamgaon MIDC", "Malkapur", "Shegaon"],
    Washim: ["Washim MIDC", "Karanja"],
    Yavatmal: ["Yavatmal MIDC", "Pusad", "Wani"],
    Ratnagiri: ["Lote Parshuram MIDC", "Ratnagiri MIDC", "Chiplun MIDC", "Khed"],
    Sindhudurg: ["Kudal MIDC", "Sawantwadi", "Kankavli"],
    Gondia: ["Gondia MIDC", "Tirora"],
    Bhandara: ["Bhandara MIDC", "Tumsar"],
  },

  Gujarat: {
    Ahmedabad: [
      "Vatva GIDC",
      "Naroda GIDC",
      "Odhav GIDC",
      "Narol",
      "Changodar",
      "Sanand GIDC",
      "Aslali",
      "Bavla",
    ],
    Vadodara: [
      "Makarpura GIDC",
      "Nandesari GIDC",
      "Savli GIDC",
      "Por GIDC",
      "Waghodia GIDC",
      "Padra",
    ],
    Bharuch: ["Ankleshwar GIDC", "Dahej GIDC", "Jhagadia GIDC", "Panoli GIDC", "Vagra", "Vilayat GIDC"],
    Valsad: ["Vapi GIDC", "Sarigam GIDC", "Umbergaon GIDC", "Pardi", "Valsad GIDC"],
    Navsari: ["Navsari GIDC", "Bilimora", "Gandevi", "Vijalpore"],
    Surat: ["Pandesara GIDC", "Sachin GIDC", "Udhna", "Katargam", "Hazira", "Olpad", "Palsana", "Kadodara"],
    Rajkot: ["Aji GIDC", "Shapar Veraval", "Metoda GIDC", "Lodhika", "Gondal", "Jetpur", "Bhaktinagar"],
    Morbi: ["Morbi", "Wankaner", "Halvad", "Tankara", "Lakhdhirpur Road Morbi"],
    Jamnagar: ["Dared GIDC", "Jamnagar GIDC", "Lalpur", "Dhrol"],
    Bhavnagar: ["Chitra GIDC", "Sihor", "Vartej", "Alang", "Mahuva"],
    Gandhinagar: ["Kalol GIDC", "Chhatral GIDC", "Santej", "Gandhinagar GIDC", "Dehgam", "Adalaj"],
    Mehsana: ["Mehsana GIDC", "Kadi", "Vijapur", "Unjha", "Visnagar"],
    Kutch: ["Gandhidham", "Anjar", "Mundra", "Bhuj", "Bhachau", "Mithi Rohar GIDC"],
    Anand: ["Vitthal Udyognagar GIDC", "Anand GIDC", "Petlad", "Borsad", "Khambhat"],
    Kheda: ["Nadiad GIDC", "Kheda", "Kapadvanj"],
    Panchmahal: ["Halol GIDC", "Godhra", "Kalol Panchmahal"],
    Sabarkantha: ["Himatnagar GIDC", "Idar", "Talod", "Prantij"],
    Surendranagar: ["Wadhwan GIDC", "Surendranagar", "Dhrangadhra", "Thangadh"],
    Junagadh: ["Junagadh GIDC", "Keshod", "Manavadar"],
    "Gir Somnath": ["Veraval", "Kodinar", "Una"],
    Amreli: ["Amreli GIDC", "Savarkundla", "Rajula"],
    Patan: ["Patan GIDC", "Chanasma", "Sidhpur"],
    Banaskantha: ["Deesa", "Palanpur GIDC", "Dhanera"],
    Tapi: ["Vyara", "Songadh"],
    Narmada: ["Rajpipla", "Dediapada"],
    Dahod: ["Dahod GIDC", "Jhalod"],
    Porbandar: ["Porbandar GIDC", "Ranavav"],
    "Devbhumi Dwarka": ["Khambhalia", "Salaya"],
    Botad: ["Botad GIDC", "Gadhada"],
    Aravalli: ["Modasa", "Bayad"],
    Mahisagar: ["Lunawada", "Balasinor"],
    "Chhota Udaipur": ["Bodeli", "Chhota Udaipur"],
  },

  Goa: {
    "North Goa": ["Verna Industrial Estate", "Bicholim Industrial Estate", "Mapusa Industrial Estate", "Pilerne", "Tivim"],
    "South Goa": ["Verna", "Kundaim Industrial Estate", "Margao", "Cuncolim Industrial Estate", "Sancoale"],
  },

  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa", "Masat Industrial Estate", "Dadra", "Khadoli"],
    Daman: ["Daman", "Bhimpore", "Kachigam"],
  },

  // ── South ─────────────────────────────────────────────────
  Karnataka: {
    "Bengaluru Urban": [
      "Peenya Industrial Area",
      "Rajajinagar Industrial Estate",
      "Bommasandra Industrial Area",
      "Jigani Industrial Area",
      "Attibele Industrial Area",
      "Electronic City",
      "Whitefield",
      "Mahadevapura",
      "Yeshwanthpur Industrial Suburb",
      "Kumbalgodu Industrial Area",
    ],
    "Bengaluru Rural": [
      "Dabaspet Industrial Area",
      "Nelamangala",
      "Hoskote Industrial Area",
      "Doddaballapur Industrial Area",
      "Devanahalli",
    ],
    Ramanagara: ["Bidadi Industrial Area", "Harohalli Industrial Area", "Kanakapura", "Channapatna"],
    Kolar: ["Narasapura Industrial Area", "Vemagal Industrial Area", "Kolar", "Bangarapet"],
    Chikkaballapura: ["Chikkaballapur Industrial Area", "Gauribidanur", "Sidlaghatta"],
    Tumakuru: [
      "Antharasanahalli Industrial Area",
      "Hirehalli Industrial Area",
      "Vasanthanarasapura Industrial Area",
      "Sira",
      "Tiptur",
    ],
    Mysuru: [
      "Hebbal Industrial Area Mysuru",
      "Metagalli Industrial Area",
      "Belagola Industrial Area",
      "Hootagalli Industrial Area",
      "Thandya Industrial Area Nanjangud",
      "Nanjangud",
    ],
    Mandya: ["Mandya Industrial Area", "Maddur", "Malavalli", "Srirangapatna", "Nagamangala"],
    Chamarajanagara: ["Badanaguppe Kellamballi Industrial Area", "Kollegal", "Gundlupet"],
    Hassan: ["Hassan Growth Centre", "Arsikere", "Channarayapatna", "Holenarsipur", "Sakleshpur"],
    "Dakshina Kannada": [
      "Baikampady Industrial Area",
      "Yeyyadi Industrial Area",
      "Thokur",
      "Puttur",
      "Bantwal",
      "Mulki",
    ],
    Udupi: ["Shivalli Industrial Area Manipal", "Nandikur", "Kundapura", "Karkala", "Padubidri"],
    "Uttara Kannada": ["Karwar", "Dandeli", "Sirsi", "Bhatkal", "Honnavar", "Haliyal"],
    Shivamogga: ["Machenahalli Industrial Area", "Bhadravathi", "Sagar", "Shikaripura", "Sorab"],
    Chikkamagaluru: ["Chikkamagaluru Industrial Area", "Kadur", "Tarikere", "Birur"],
    Chitradurga: ["Chitradurga Industrial Area", "Hiriyur", "Challakere", "Hosadurga"],
    Davanagere: ["Davangere Industrial Area", "Harihar", "Lokikere", "Channagiri"],
    Ballari: ["Ballari Industrial Area", "Sandur", "Kudligi", "Siruguppa"],
    Vijayanagara: ["Hosapete", "Toranagallu", "Kottur", "Harapanahalli", "Hagaribommanahalli"],
    Koppala: ["Koppal Industrial Area", "Ginigera", "Gangavathi", "Kukanoor", "Yelburga"],
    Raichuru: ["Raichur Growth Centre", "Shaktinagar", "Sindhanur", "Manvi", "Devadurga"],
    Yadgiri: ["Kadechur Badiyal Industrial Area", "Yadgir", "Shahapur", "Surapura"],
    Kalaburagi: [
      "Kapanoor Industrial Area",
      "Nandur Keshwar Industrial Area",
      "Wadi",
      "Sedam",
      "Aland",
      "Chittapur",
    ],
    Bidar: ["Kolhar Industrial Area", "Humnabad Industrial Area", "Bhalki", "Basavakalyan", "Aurad"],
    Vijayapura: ["Vijayapura Industrial Area", "Indi", "Sindagi", "Basavana Bagewadi", "Muddebihal"],
    Bagalakote: [
      "Bagalkot Industrial Area",
      "Mudhol",
      "Jamkhandi",
      "Mahalingapura",
      "Ilkal",
      "Rabkavi Banhatti",
    ],
    Belagavi: [
      "Udyambag Industrial Area",
      "Auto Nagar Belagavi",
      "Machhe Industrial Area",
      "Honaga Industrial Area",
      "Kanbargi",
      "Gokak",
      "Nipani",
      "Chikkodi",
      "Hukkeri",
      "Mudalagi",
      "Khanapur",
    ],
    Dharwada: [
      "Belur Industrial Area Dharwad",
      "Gokul Road Hubballi",
      "Tarihal Industrial Area",
      "Rayapur Dharwad",
      "Navanagar Hubballi",
      "Kalghatgi",
    ],
    Gadaga: ["Gadag Industrial Area", "Narayanpur Gadag", "Mundargi", "Ron", "Naragund", "Gajendragad"],
    Haveri: ["Ranebennur", "Haveri Industrial Area", "Byadgi", "Hirekerur", "Savanur", "Shiggaon", "Hangal"],
    Kodagu: ["Kushalnagar", "Madikeri", "Somwarpet", "Virajpet"],
  },

  "Tamil Nadu": {
    Chennai: ["Ambattur Industrial Estate", "Guindy Industrial Estate", "Perungudi", "Ekkattuthangal"],
    Tiruvallur: ["Gummidipoondi SIPCOT", "Manali Industrial Area", "Red Hills", "Tiruvallur", "Poonamallee"],
    Kanchipuram: ["Sriperumbudur SIPCOT", "Irungattukottai SIPCOT", "Oragadam", "Kanchipuram", "Walajabad"],
    Chengalpattu: ["Maraimalai Nagar", "Chengalpattu SIPCOT", "Mahindra World City", "Thiruporur"],
    Coimbatore: [
      "SIDCO Industrial Estate Coimbatore",
      "Peelamedu",
      "Ganapathy",
      "Kurichi Industrial Estate",
      "Sulur",
      "Pollachi",
      "Mettupalayam",
      "Annur",
    ],
    Tiruppur: ["Tiruppur", "Avinashi", "Palladam", "Udumalaipettai", "Dharapuram"],
    Erode: ["Perundurai SIPCOT", "Chithode", "Gobichettipalayam", "Bhavani", "Sathyamangalam"],
    Salem: ["Salem SIDCO Industrial Estate", "Omalur", "Mettur", "Attur", "Edappadi"],
    Namakkal: ["Namakkal", "Rasipuram", "Tiruchengode", "Komarapalayam", "Paramathi Velur"],
    Krishnagiri: ["Hosur SIPCOT", "Hosur", "Krishnagiri", "Bargur", "Denkanikottai"],
    Ranipet: ["Ranipet SIPCOT", "Arakkonam", "Walajapet", "Sholinghur"],
    Vellore: ["Vellore", "Gudiyatham", "Katpadi"],
    Tirupattur: ["Ambur", "Vaniyambadi", "Tirupattur", "Jolarpettai"],
    Cuddalore: ["Cuddalore SIPCOT", "Neyveli", "Panruti", "Chidambaram"],
    Thoothukudi: ["Thoothukudi SIPCOT", "Kovilpatti", "Tuticorin Port", "Ettayapuram"],
    Virudhunagar: ["Sivakasi", "Virudhunagar", "Rajapalayam", "Aruppukkottai", "Srivilliputhur"],
    Madurai: ["Kappalur Industrial Estate", "Madurai SIDCO", "Thirumangalam", "Melur"],
    Tiruchirappalli: ["Thuvakudi", "Tiruchirappalli SIDCO", "Manapparai", "Lalgudi"],
    Karur: ["Karur", "Pugalur", "Kulithalai", "Velayuthampalayam"],
    Dindigul: ["Dindigul", "Palani", "Vedasandur", "Oddanchatram"],
    Thanjavur: ["Thanjavur", "Kumbakonam", "Pattukkottai"],
    Tirunelveli: ["Tirunelveli", "Nanguneri SIPCOT", "Palayamkottai"],
    Tenkasi: ["Tenkasi", "Sankarankovil", "Rajapalayam Road Tenkasi"],
    Kanyakumari: ["Nagercoil", "Marthandam", "Kanyakumari SIDCO"],
    Theni: ["Theni", "Cumbum", "Bodinayakanur"],
    Dharmapuri: ["Dharmapuri", "Harur", "Palacode"],
    Pudukkottai: ["Pudukkottai", "Aranthangi"],
    Sivaganga: ["Karaikudi", "Sivaganga", "Manamadurai"],
    Viluppuram: ["Viluppuram", "Tindivanam"],
    Tiruvannamalai: ["Tiruvannamalai", "Arani", "Cheyyar SIPCOT"],
    Nagapattinam: ["Nagapattinam", "Velankanni"],
    Ariyalur: ["Ariyalur", "Jayankondam"],
    Perambalur: ["Perambalur"],
    Ramanathapuram: ["Ramanathapuram", "Paramakudi"],
  },

  Kerala: {
    Ernakulam: [
      "Kalamassery Industrial Estate",
      "Eloor",
      "Angamaly",
      "Perumbavoor",
      "Aluva",
      "Kakkanad",
      "Muvattupuzha",
    ],
    Thrissur: ["Thrissur", "Irinjalakuda", "Chalakudy", "Kodungallur", "Athani Industrial Area"],
    Kozhikode: ["Kozhikode", "Feroke", "Kinfra Park Kakkancheri", "Vadakara"],
    Malappuram: ["Manjeri", "Tirur", "Perinthalmanna", "Nilambur"],
    Palakkad: ["Kanjikode Industrial Area", "Palakkad", "Ottapalam", "Shoranur"],
    Kollam: ["Kollam", "Chavara", "Kundara", "Punalur"],
    Thiruvananthapuram: ["Thiruvananthapuram", "Attingal", "Neyyattinkara", "Kazhakkoottam"],
    Alappuzha: ["Alappuzha", "Cherthala", "Kayamkulam", "Mavelikkara"],
    Kottayam: ["Kottayam", "Changanassery", "Pala", "Vaikom"],
    Kannur: ["Kannur", "Thalassery", "Payyanur", "Kinfra Park Kannur"],
    Kasaragod: ["Kasaragod", "Kanhangad", "Nileshwar"],
    Idukki: ["Thodupuzha", "Kattappana"],
    Pathanamthitta: ["Pathanamthitta", "Adoor", "Thiruvalla"],
    Wayanad: ["Kalpetta", "Sultan Bathery"],
  },

  Telangana: {
    Hyderabad: ["Balanagar", "Sanathnagar Industrial Estate", "Azamabad Industrial Area", "Moosapet"],
    "Medchal–Malkajgiri": [
      "Jeedimetla Industrial Area",
      "Bollaram Industrial Area",
      "Cherlapally Industrial Estate",
      "Nacharam Industrial Estate",
      "Uppal",
      "Medchal",
      "Kushaiguda",
    ],
    "Ranga Reddy": ["Katedan Industrial Area", "Shamshabad", "Shadnagar", "Mahadevpur", "Kothur"],
    Sangareddy: ["Patancheru", "Pashamylaram", "Bonthapally", "Zaheerabad", "Sangareddy", "Isnapur"],
    Medak: ["Medak", "Narsapur", "Toopran"],
    Nizamabad: ["Nizamabad", "Bodhan", "Armoor"],
    Karimnagar: ["Karimnagar", "Jammikunta", "Huzurabad"],
    Hanamkonda: ["Hanamkonda", "Kazipet"],
    Warangal: ["Warangal", "Mamnoor", "Narsampet"],
    Khammam: ["Khammam", "Sathupalli", "Madhira"],
    "Bhadradri Kothagudem": ["Kothagudem", "Palwancha", "Manuguru"],
    Nalgonda: ["Nalgonda", "Miryalaguda", "Nandikonda"],
    Suryapet: ["Suryapet", "Kodad", "Huzurnagar"],
    Siddipet: ["Siddipet", "Gajwel", "Husnabad"],
    Mahbubnagar: ["Mahbubnagar", "Jadcherla", "Badepally"],
    Adilabad: ["Adilabad", "Bhainsa"],
    Mancherial: ["Mancherial", "Bellampalli", "Chennur"],
    Peddapalli: ["Ramagundam", "Peddapalli", "Godavarikhani"],
    Jagtial: ["Jagtial", "Korutla"],
    Vikarabad: ["Vikarabad", "Tandur"],
    "Yadadri Bhuvanagiri": ["Bhongir", "Choutuppal", "Yadagirigutta"],
    Nirmal: ["Nirmal", "Bhainsa Nirmal"],
    Kamareddy: ["Kamareddy", "Banswada"],
  },

  "Andhra Pradesh": {
    Visakhapatnam: ["Autonagar Visakhapatnam", "Gajuwaka", "Duvvada", "Pendurthi"],
    Anakapalli: ["Atchutapuram", "Parawada", "Anakapalli", "Narsipatnam"],
    NTR: ["Autonagar Vijayawada", "Vijayawada", "Nunna", "Kondapalli"],
    Krishna: ["Machilipatnam", "Gudivada", "Pedana"],
    Guntur: ["Autonagar Guntur", "Guntur", "Tenali", "Mangalagiri"],
    Bapatla: ["Chirala", "Bapatla", "Repalle"],
    Palnadu: ["Narasaraopet", "Sattenapalli", "Macherla", "Piduguralla"],
    Prakasam: ["Ongole", "Markapur", "Kanigiri"],
    "Sri Potti Sriramulu Nellore": ["Nellore", "Kavali", "Gudur", "Naidupeta"],
    Tirupati: ["Sri City", "Renigunta", "Tirupati", "Srikalahasti", "Gudur Tirupati"],
    Chittoor: ["Chittoor", "Palamaner", "Madanapalle"],
    Kurnool: ["Kurnool", "Adoni", "Yemmiganur"],
    Nandyal: ["Nandyal", "Dhone", "Allagadda"],
    Ananthapuramu: ["Anantapur", "Hindupur", "Guntakal", "Tadipatri"],
    YSR: ["Kadapa", "Proddatur", "Jammalamadugu"],
    Kakinada: ["Autonagar Kakinada", "Kakinada", "Peddapuram", "Samalkot"],
    "East Godavari": ["Rajamahendravaram", "Kovvur", "Nidadavole"],
    "West Godavari": ["Bhimavaram", "Tadepalligudem", "Palakollu", "Narsapur"],
    Eluru: ["Eluru", "Chintalapudi", "Jangareddygudem"],
    Srikakulam: ["Srikakulam", "Palasa", "Amadalavalasa"],
    Vizianagaram: ["Vizianagaram", "Bobbili", "Parvathipuram"],
    "Dr. B.R. Ambedkar Konaseema": ["Amalapuram", "Ramachandrapuram"],
    "Sri Sathya Sai": ["Dharmavaram", "Puttaparthi", "Kadiri"],
    Annamayya: ["Rayachoti", "Madanapalle Annamayya", "Rajampet"],
  },

  Puducherry: {
    Puducherry: ["Mettupalayam Industrial Estate Puducherry", "Thattanchavady", "Sedarapet", "Puducherry"],
    Karaikal: ["Karaikal"],
  },

  // ── North ─────────────────────────────────────────────────
  "National Capital Territory of Delhi": {
    "North West Delhi": ["Bawana Industrial Area", "Narela Industrial Area", "Wazirpur Industrial Area", "Badli Industrial Area"],
    "West Delhi": ["Mayapuri Industrial Area", "Kirti Nagar", "Udyog Nagar", "Naraina Industrial Area"],
    "South West Delhi": ["Okhla Industrial Area", "Najafgarh Road Industrial Area", "Kapashera"],
    "South East Delhi": ["Okhla Industrial Estate", "Govindpuri"],
    "North East Delhi": ["Jhilmil Industrial Area", "Karawal Nagar"],
    "East Delhi": ["Patparganj Industrial Area", "Shahdara"],
    "North Delhi": ["Lawrence Road Industrial Area", "Azadpur"],
  },

  Haryana: {
    Gurugram: ["Udyog Vihar Gurugram", "IMT Manesar", "Manesar", "Binola", "Sohna", "Pataudi"],
    Faridabad: ["Faridabad Industrial Area", "Ballabgarh", "NIT Faridabad", "Sector 59 Faridabad"],
    Sonipat: ["Kundli Industrial Area", "Rai Industrial Area", "Barhi Industrial Area", "Sonipat", "Gannaur"],
    Jhajjar: ["IMT Bahadurgarh", "Bahadurgarh", "Jhajjar"],
    Rewari: ["Dharuhera", "Bawal Industrial Area", "Rewari"],
    Panipat: ["Panipat Industrial Area", "Samalkha"],
    Rohtak: ["IMT Rohtak", "Rohtak"],
    Hisar: ["Hisar Industrial Area", "Hansi"],
    Yamunanagar: ["Yamunanagar", "Jagadhri"],
    Ambala: ["Ambala Cantt", "Ambala City", "Barara"],
    Karnal: ["Karnal Industrial Area", "Gharaunda", "Taraori"],
    Kurukshetra: ["Kurukshetra", "Shahabad Markanda", "Pehowa"],
    Panchkula: ["Panchkula Industrial Area", "Barwala"],
    Palwal: ["Palwal", "Hodal"],
    Bhiwani: ["Bhiwani", "Charkhi Dadri Road Bhiwani"],
    Mahendragarh: ["Narnaul"],
    Nuh: ["Nuh", "Tauru"],
    Sirsa: ["Sirsa"],
    Jind: ["Jind"],
    Kaithal: ["Kaithal"],
  },

  Punjab: {
    Ludhiana: ["Focal Point Ludhiana", "Ludhiana Industrial Area", "Sahnewal", "Khanna", "Doraha", "Jagraon"],
    Jalandhar: ["Focal Point Jalandhar", "Jalandhar Industrial Area", "Nakodar", "Goraya"],
    Amritsar: ["Focal Point Amritsar", "Amritsar Industrial Area", "Majitha Road Amritsar"],
    "Sahibzada Ajit Singh Nagar": ["Mohali Industrial Area", "Dera Bassi", "Lalru", "Kharar", "Banur"],
    "Fatehgarh Sahib": ["Mandi Gobindgarh", "Sirhind", "Khamano"],
    Patiala: ["Patiala Industrial Area", "Rajpura", "Nabha", "Samana"],
    Rupnagar: ["Ropar", "Nangal", "Morinda"],
    Kapurthala: ["Phagwara", "Kapurthala", "Sultanpur Lodhi"],
    Hoshiarpur: ["Hoshiarpur Industrial Area", "Mukerian", "Dasuya"],
    Sangrur: ["Sangrur", "Sunam", "Dhuri", "Lehragaga"],
    Bathinda: ["Bathinda Industrial Area", "Goniana"],
    Gurdaspur: ["Batala", "Gurdaspur", "Dinanagar"],
    Moga: ["Moga Industrial Area", "Baghapurana"],
    Firozpur: ["Firozpur", "Zira"],
    Faridkot: ["Faridkot", "Kotkapura"],
    Barnala: ["Barnala Industrial Area", "Tapa"],
    Mansa: ["Mansa", "Budhlada"],
    "Sri Muktsar Sahib": ["Sri Muktsar Sahib", "Malout"],
    Malerkotla: ["Malerkotla", "Ahmedgarh"],
    "Shahid Bhagat Singh Nagar": ["Nawanshahr", "Banga"],
    Pathankot: ["Pathankot"],
    Fazilka: ["Abohar", "Fazilka", "Jalalabad"],
    "Tarn Taran": ["Tarn Taran", "Patti"],
  },

  Chandigarh: {
    Chandigarh: ["Chandigarh Industrial Area Phase 1", "Chandigarh Industrial Area Phase 2"],
  },

  Rajasthan: {
    Jaipur: [
      "Vishwakarma Industrial Area",
      "Sitapura Industrial Area",
      "Malviya Nagar Industrial Area",
      "Bagru",
      "Kukas",
      "Jaitpura",
      "Chomu",
      "Sanganer",
    ],
    Alwar: ["Bhiwadi", "Neemrana", "Khushkhera", "Tapukara", "Chopanki", "Behror", "Alwar Industrial Area"],
    Jodhpur: ["Boranada Industrial Area", "Basni Industrial Area", "Sangariya Jodhpur", "Jodhpur"],
    Ajmer: ["Kishangarh", "Beawar", "Ajmer Industrial Area", "Parbatsar"],
    Bhilwara: ["Bhilwara Industrial Area", "Gangapur Bhilwara", "Mandalgarh"],
    Kota: ["Kota Industrial Area", "Ranpur Industrial Area Kota", "Sangod"],
    Udaipur: ["Madri Industrial Area", "Debari", "Udaipur Industrial Area"],
    Pali: ["Pali Industrial Area", "Sumerpur", "Marwar Junction"],
    Bikaner: ["Karni Industrial Area Bikaner", "Bikaner", "Nokha"],
    Sikar: ["Sikar Industrial Area", "Neem Ka Thana", "Khandela"],
    Jhunjhunu: ["Jhunjhunu", "Chirawa", "Bissau"],
    "Sri Ganganagar": ["Sri Ganganagar", "Suratgarh", "Padampur"],
    Hanumangarh: ["Hanumangarh", "Nohar"],
    Chittorgarh: ["Nimbahera", "Chittorgarh Industrial Area", "Begun"],
    Rajsamand: ["Rajsamand", "Nathdwara", "Kankroli"],
    Bharatpur: ["Bharatpur Industrial Area", "Deeg"],
    Nagaur: ["Makrana", "Kuchaman City", "Nagaur"],
    Barmer: ["Balotra", "Barmer"],
    Sirohi: ["Abu Road", "Sheoganj", "Sirohi"],
    Jalore: ["Jalore", "Bhinmal"],
    Dausa: ["Dausa", "Bandikui"],
    Tonk: ["Tonk", "Malpura"],
    Bundi: ["Bundi", "Lakheri"],
    Jhalawar: ["Jhalawar", "Bhawani Mandi"],
    Churu: ["Churu", "Ratangarh", "Sujangarh"],
    Karauli: ["Hindaun", "Karauli"],
    Banswara: ["Banswara"],
    Dungarpur: ["Dungarpur"],
    Baran: ["Baran"],
    "Sawai Madhopur": ["Sawai Madhopur"],
    Dholpur: ["Dholpur"],
    Jaisalmer: ["Jaisalmer"],
  },

  "Uttar Pradesh": {
    "Gautam Buddha Nagar": ["Noida", "Greater Noida", "Noida Phase 2", "Surajpur", "Ecotech Greater Noida", "Dadri"],
    Ghaziabad: ["Sahibabad Industrial Area", "Ghaziabad Industrial Area", "Loni", "Modinagar", "Bulandshahr Road Industrial Area"],
    "Kanpur Nagar": ["Panki Industrial Area", "Dada Nagar Industrial Area", "Fazalganj Industrial Area", "Jajmau"],
    "Kanpur Dehat": ["Rania Industrial Area", "Akbarpur"],
    Lucknow: ["Amausi Industrial Area", "Talkatora Industrial Area", "Chinhat Industrial Area", "Sarojini Nagar"],
    Agra: ["Sikandra Industrial Area", "Foundry Nagar Agra", "Runakta", "Agra"],
    Meerut: ["Partapur Industrial Area", "Mohkampur Industrial Area", "Meerut"],
    Moradabad: ["Moradabad Industrial Area", "Katghar", "Moradabad"],
    Varanasi: ["Ramnagar Industrial Estate", "Chandpur Industrial Estate Varanasi", "Varanasi"],
    Prayagraj: ["Naini Industrial Area", "Prayagraj"],
    Aligarh: ["Talanagri Industrial Area", "Aligarh"],
    Bareilly: ["Parsakhera Industrial Area", "Bareilly"],
    Gorakhpur: ["GIDA Gorakhpur", "Gorakhpur"],
    Saharanpur: ["Saharanpur Industrial Area", "Deoband"],
    Muzaffarnagar: ["Muzaffarnagar Industrial Area", "Khatauli", "Bhopa Road Muzaffarnagar"],
    Firozabad: ["Firozabad", "Tundla"],
    Mathura: ["Kosi Kalan", "Mathura Industrial Area", "Vrindavan"],
    Hapur: ["Hapur", "Pilkhuwa"],
    Bulandshahr: ["Sikandrabad Industrial Area", "Khurja", "Bulandshahr"],
    Jhansi: ["Bijauli Industrial Area", "Jhansi"],
    Unnao: ["Unnao Industrial Area", "Shuklaganj"],
    Sonbhadra: ["Renukoot", "Obra", "Anpara"],
    Bhadohi: ["Bhadohi", "Gopiganj"],
    Mau: ["Maunath Bhanjan", "Mau"],
    Kannauj: ["Kannauj", "Chhibramau"],
    Amethi: ["Jagdishpur Industrial Area", "Amethi"],
    Bijnor: ["Bijnor", "Najibabad", "Dhampur"],
    Shamli: ["Shamli", "Kairana"],
    Bagpat: ["Baraut", "Baghpat"],
    Amroha: ["Amroha", "Hasanpur"],
    Sambhal: ["Chandausi", "Sambhal"],
    Rampur: ["Rampur Industrial Area", "Bilaspur Rampur"],
    Auraiya: ["Dibiyapur", "Auraiya"],
    Etawah: ["Etawah"],
    Farrukhabad: ["Fatehgarh", "Farrukhabad"],
    Jalaun: ["Orai", "Konch"],
    Ayodhya: ["Ayodhya", "Faizabad"],
    Sitapur: ["Sitapur"],
    Hardoi: ["Hardoi"],
    Shahjahanpur: ["Shahjahanpur"],
    Barabanki: ["Barabanki Industrial Area"],
    Raebareli: ["Raebareli"],
    Sultanpur: ["Sultanpur"],
    Jaunpur: ["Jaunpur"],
    Azamgarh: ["Azamgarh"],
    Mirzapur: ["Mirzapur"],
    Chandauli: ["Chandauli"],
    Ghazipur: ["Ghazipur"],
    Deoria: ["Deoria"],
    Basti: ["Basti"],
    Gonda: ["Gonda"],
    Bahraich: ["Bahraich"],
    "Lakhimpur Kheri": ["Lakhimpur"],
    Pilibhit: ["Pilibhit"],
    Budaun: ["Budaun"],
    Hathras: ["Hathras"],
    Etah: ["Etah"],
    Mainpuri: ["Mainpuri"],
    Banda: ["Banda"],
    Fatehpur: ["Fatehpur"],
    Lalitpur: ["Lalitpur"],
    Pratapgarh: ["Pratapgarh"],
  },

  Uttarakhand: {
    Haridwar: ["SIDCUL Haridwar", "Bahadrabad", "Roorkee", "Laksar"],
    "Udham Singh Nagar": ["SIDCUL Pantnagar", "Rudrapur", "Kashipur", "Sitarganj", "Bazpur", "Jaspur"],
    Dehradun: ["Selaqui Industrial Area", "Dehradun", "Vikasnagar", "Doiwala"],
    Nainital: ["Haldwani", "Lalkuan"],
    "Pauri Garhwal": ["Kotdwar", "Srinagar Garhwal"],
    Almora: ["Almora"],
  },

  "Himachal Pradesh": {
    Solan: ["Baddi", "Barotiwala", "Nalagarh", "Parwanoo", "Solan"],
    Sirmaur: ["Paonta Sahib", "Kala Amb", "Nahan"],
    Una: ["Mehatpur Industrial Area", "Una", "Amb", "Tahliwal"],
    Kangra: ["Kangra", "Nagrota Bagwan", "Sansarpur Terrace"],
    Bilaspur: ["Bilaspur Himachal", "Ghumarwin"],
    Shimla: ["Shimla", "Theog"],
    Mandi: ["Mandi", "Sundernagar", "Nerchowk"],
    Hamirpur: ["Hamirpur Himachal", "Bhota"],
    Chamba: ["Chamba"],
    Kullu: ["Kullu", "Bhuntar"],
  },

  "Jammu and Kashmir": {
    Jammu: ["Bari Brahmana Industrial Area", "Gangyal Industrial Area", "Jammu", "Bari Brahmana"],
    Samba: ["Samba Industrial Area", "Vijaypur"],
    Kathua: ["Kathua Industrial Area", "Hiranagar"],
    Srinagar: ["Srinagar Industrial Estate", "Zakura", "Rangreth"],
    Budgam: ["Ompora Industrial Estate", "Budgam"],
    Baramulla: ["Baramulla", "Sopore"],
    Anantnag: ["Anantnag", "Bijbehara"],
    Udhampur: ["Udhampur"],
    Pulwama: ["Lassipora Industrial Estate", "Pulwama"],
  },

  // ── Central ───────────────────────────────────────────────
  "Madhya Pradesh": {
    Indore: ["Pithampur", "Sanwer Road Industrial Area", "Indore", "Rau", "Dewas Naka Indore"],
    Bhopal: ["Govindpura Industrial Area", "Mandideep", "Bhopal", "Bairagarh"],
    Dhar: ["Pithampur Dhar", "Dhar", "Badnawar"],
    Dewas: ["Dewas Industrial Area", "Dewas", "Bagli"],
    Jabalpur: ["Richhai Industrial Area", "Adhartal", "Jabalpur", "Panagar"],
    Gwalior: ["Maharajpura Industrial Area", "Banmore", "Gwalior", "Malanpur"],
    Ujjain: ["Ujjain Industrial Area", "Nagda", "Ujjain"],
    Ratlam: ["Ratlam Industrial Area", "Jaora"],
    Mandsaur: ["Mandsaur", "Neemuch Road Mandsaur"],
    Neemuch: ["Neemuch", "Manasa"],
    Sagar: ["Sagar Industrial Area", "Bina", "Khurai"],
    Satna: ["Satna Industrial Area", "Maihar", "Satna"],
    Rewa: ["Rewa Industrial Area", "Rewa"],
    Katni: ["Katni Industrial Area", "Katni"],
    Singrauli: ["Singrauli", "Waidhan"],
    Khargone: ["Khargone", "Barwaha", "Sanawad"],
    Khandwa: ["Khandwa", "Pandhana"],
    Burhanpur: ["Burhanpur", "Nepanagar"],
    Chhindwara: ["Chhindwara", "Parasia"],
    Balaghat: ["Balaghat", "Waraseoni"],
    Shivpuri: ["Shivpuri", "Badarwas"],
    Morena: ["Banmore Industrial Area", "Morena"],
    Bhind: ["Malanpur Industrial Area", "Bhind", "Gohad"],
    Vidisha: ["Vidisha", "Ganj Basoda"],
    Raisen: ["Mandideep Raisen", "Raisen", "Obaidullaganj"],
    Sehore: ["Sehore", "Ashta"],
    Shajapur: ["Shajapur", "Shujalpur"],
    Rajgarh: ["Rajgarh", "Biaora"],
    Guna: ["Guna Industrial Area", "Guna"],
    Hoshangabad: ["Hoshangabad", "Itarsi", "Babai"],
    Betul: ["Betul", "Sarni"],
    Damoh: ["Damoh"],
    Chhatarpur: ["Chhatarpur"],
    Narsinghpur: ["Narsinghpur", "Gadarwara"],
    Seoni: ["Seoni"],
    Shahdol: ["Shahdol"],
    Jhabua: ["Jhabua", "Meghnagar"],
    Barwani: ["Barwani", "Sendhwa"],
    "Agar Malwa": ["Agar"],
    Harda: ["Harda"],
    Panna: ["Panna"],
    Datia: ["Datia"],
  },

  Chhattisgarh: {
    Raipur: ["Urla Industrial Area", "Siltara Industrial Area", "Bhanpuri", "Raipur", "Tilda"],
    Durg: ["Bhilai", "Borai Industrial Area", "Durg", "Kumhari"],
    Bilaspur: ["Sirgitti Industrial Area", "Tifra", "Bilaspur"],
    Raigarh: ["Raigarh Industrial Area", "Kharsia", "Raigarh"],
    Korba: ["Korba Industrial Area", "Korba"],
    "Janjgir-Champa": ["Champa", "Janjgir", "Akaltara"],
    Rajnandgaon: ["Rajnandgaon Industrial Area", "Dongargarh"],
    Mahasamund: ["Mahasamund", "Bagbahara"],
    Dhamtari: ["Dhamtari"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara"],
    Balod: ["Balod", "Dalli Rajhara"],
    Bemetara: ["Bemetara"],
    Jashpur: ["Jashpur"],
    Surguja: ["Ambikapur"],
    Kabirdham: ["Kawardha"],
    Bastar: ["Jagdalpur"],
    Mungeli: ["Mungeli"],
  },

  // ── East and North-East ───────────────────────────────────
  "West Bengal": {
    Howrah: ["Dankuni", "Howrah Industrial Area", "Liluah", "Bally", "Santragachi", "Jagadishpur Howrah"],
    Kolkata: ["Taratala Industrial Area", "Tangra", "Topsia", "Kolkata"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Kalyani Industrial Area", "Naihati", "Madhyamgram"],
    "South 24 Parganas": ["Falta SEZ", "Budge Budge", "Maheshtala", "Baruipur"],
    Hooghly: ["Serampore", "Rishra", "Chinsurah", "Dankuni Hooghly", "Bansberia", "Tarakeswar"],
    "Paschim Bardhaman": ["Durgapur Industrial Area", "Asansol", "Raniganj", "Kulti", "Burnpur"],
    "Purba Bardhaman": ["Burdwan", "Kalna", "Katwa"],
    Nadia: ["Kalyani", "Ranaghat", "Krishnanagar", "Haringhata"],
    "Paschim Medinipur": ["Kharagpur", "Midnapore", "Ghatal"],
    "Purba Medinipur": ["Haldia Industrial Area", "Haldia", "Tamluk", "Contai"],
    Darjeeling: ["Siliguri Industrial Area", "Siliguri", "Darjeeling"],
    Jalpaiguri: ["Jalpaiguri", "Dhupguri", "Mal Bazar"],
    Maldah: ["Malda", "English Bazar"],
    Murshidabad: ["Berhampore", "Jangipur", "Domkal"],
    Birbhum: ["Bolpur", "Suri", "Rampurhat"],
    Bankura: ["Bankura", "Bishnupur"],
    Purulia: ["Purulia", "Raghunathpur"],
    "Cooch Behar": ["Cooch Behar", "Dinhata"],
    "Uttar Dinajpur": ["Raiganj", "Islampur Dinajpur"],
    "Dakshin Dinajpur": ["Balurghat", "Gangarampur"],
  },

  Odisha: {
    Khordha: ["Bhubaneswar Industrial Estate", "Khordha", "Jatni", "Mancheswar Industrial Estate"],
    Cuttack: ["Cuttack Industrial Estate", "Choudwar", "Jagatpur Industrial Estate", "Athagarh"],
    Jajpur: ["Kalinga Nagar", "Duburi", "Jajpur Road"],
    Jharsuguda: ["Jharsuguda", "Brajrajnagar", "Belpahar"],
    Sundargarh: ["Rourkela Industrial Estate", "Rourkela", "Kalunga Industrial Estate", "Rajgangpur"],
    Angul: ["Angul Industrial Area", "Talcher", "Nalco Nagar Angul"],
    Dhenkanal: ["Dhenkanal", "Kamakhyanagar"],
    Sambalpur: ["Sambalpur Industrial Estate", "Burla", "Hirakud"],
    Ganjam: ["Berhampur Industrial Estate", "Chhatrapur", "Gopalpur", "Berhampur"],
    Balasore: ["Balasore Industrial Estate", "Balasore", "Soro"],
    Bhadrak: ["Bhadrak", "Dhamra", "Chandbali"],
    Jagatsinghpur: ["Paradeep", "Jagatsinghpur"],
    Kendrapara: ["Kendrapara"],
    Puri: ["Puri", "Pipili"],
    Rayagada: ["Rayagada", "Therubali"],
    Koraput: ["Koraput", "Jeypore", "Sunabeda"],
    Kendujhar: ["Keonjhar", "Barbil", "Joda"],
    Bargarh: ["Bargarh", "Padampur Bargarh"],
    Balangir: ["Balangir", "Titlagarh"],
    Mayurbhanj: ["Baripada", "Rairangpur"],
    Kalahandi: ["Bhawanipatna", "Kesinga"],
  },

  Jharkhand: {
    "East Singhbhum": ["Adityapur Industrial Area", "Jamshedpur", "Ghatshila", "Jugsalai"],
    "Seraikela-Kharsawan": ["Adityapur", "Gamharia", "Seraikela"],
    Ranchi: ["Ranchi Industrial Area", "Tupudana Industrial Area", "Kokar Industrial Area", "Namkum"],
    Dhanbad: ["Dhanbad", "Jharia", "Sindri", "Govindpur Dhanbad"],
    Bokaro: ["Bokaro Steel City", "Bokaro Industrial Area", "Chas", "Balidih Industrial Area"],
    Ramgarh: ["Ramgarh", "Patratu", "Barkakana"],
    Hazaribag: ["Hazaribagh", "Barhi"],
    Giridih: ["Giridih"],
    Deoghar: ["Deoghar Industrial Area", "Deoghar", "Madhupur"],
    Palamu: ["Daltonganj", "Medininagar"],
    "West Singhbhum": ["Chaibasa", "Chakradharpur"],
    Koderma: ["Koderma", "Jhumri Telaiya"],
    Sahibganj: ["Sahibganj"],
    Dumka: ["Dumka"],
    Lohardaga: ["Lohardaga"],
  },

  Bihar: {
    Patna: ["Patliputra Industrial Area", "Fatuha Industrial Area", "Bihta", "Patna", "Danapur"],
    Muzaffarpur: ["Bela Industrial Area Muzaffarpur", "Muzaffarpur", "Motipur"],
    Begusarai: ["Barauni Industrial Area", "Begusarai", "Barauni"],
    Bhagalpur: ["Bhagalpur Industrial Area", "Bhagalpur", "Naugachia"],
    Gaya: ["Gaya Industrial Area", "Gaya", "Bodh Gaya", "Tekari"],
    Nalanda: ["Biharsharif", "Rajgir", "Hilsa"],
    Rohtas: ["Dalmianagar", "Sasaram", "Dehri"],
    Bhojpur: ["Ara", "Bihiya", "Koilwar"],
    Darbhanga: ["Darbhanga Industrial Area", "Darbhanga"],
    Purnia: ["Purnia Industrial Area", "Purnia", "Banmankhi"],
    Munger: ["Munger Industrial Area", "Munger", "Jamalpur"],
    Samastipur: ["Samastipur", "Rosera", "Dalsinghsarai"],
    Saran: ["Chhapra", "Marhaura", "Sonepur"],
    Siwan: ["Siwan"],
    Vaishali: ["Hajipur Industrial Area", "Hajipur", "Lalganj"],
    "East Champaran": ["Motihari", "Raxaul"],
    "West Champaran": ["Bettiah", "Bagaha", "Narkatiaganj"],
    Katihar: ["Katihar", "Barsoi"],
    Saharsa: ["Saharsa"],
    Madhubani: ["Madhubani", "Jhanjharpur"],
    Sitamarhi: ["Sitamarhi", "Dumra"],
    Nawada: ["Nawada", "Warisaliganj"],
    Aurangabad: ["Aurangabad Bihar", "Daudnagar"],
    Jamui: ["Jamui"],
    Buxar: ["Buxar", "Dumraon"],
    Kishanganj: ["Kishanganj"],
    Araria: ["Araria", "Forbesganj"],
  },

  Assam: {
    "Kamrup Metropolitan": ["Guwahati Industrial Estate", "Bamunimaidan Industrial Estate", "Guwahati", "Betkuchi"],
    Kamrup: ["Changsari", "Amingaon Industrial Growth Centre", "Rangia", "Palashbari"],
    Dibrugarh: ["Dibrugarh", "Duliajan", "Namrup", "Naharkatiya"],
    Tinsukia: ["Tinsukia", "Digboi", "Makum", "Margherita"],
    Jorhat: ["Jorhat Industrial Estate", "Jorhat", "Titabar"],
    Sivasagar: ["Sivasagar", "Nazira", "Simaluguri"],
    Nagaon: ["Nagaon Industrial Estate", "Nagaon", "Hojai", "Lumding"],
    Cachar: ["Silchar Industrial Estate", "Silchar", "Lakhipur"],
    Bongaigaon: ["Bongaigaon Industrial Area", "Bongaigaon", "New Bongaigaon"],
    Dhubri: ["Dhubri", "Gauripur"],
    Golaghat: ["Golaghat", "Numaligarh", "Bokakhat"],
    Sonitpur: ["Tezpur Industrial Estate", "Tezpur", "Dhekiajuli"],
    Barpeta: ["Barpeta", "Howly"],
    Goalpara: ["Goalpara", "Lakhipur Goalpara"],
    Karimganj: ["Karimganj", "Badarpur"],
    Nalbari: ["Nalbari"],
    Darrang: ["Mangaldoi"],
    Lakhimpur: ["North Lakhimpur"],
    "Karbi Anglong": ["Diphu"],
  },

  Tripura: {
    "West Tripura": ["Bodhjungnagar Industrial Growth Centre", "Agartala", "Dukli"],
    "South Tripura": ["Udaipur Tripura", "Belonia"],
    Gomati: ["Udaipur Gomati"],
  },

  Meghalaya: {
    "East Khasi Hills": ["Shillong", "EPIP Byrnihat", "Umiam"],
    "Ri Bhoi": ["Byrnihat", "Nongpoh"],
    "West Garo Hills": ["Tura"],
  },

  Nagaland: {
    Dimapur: ["Dimapur Industrial Estate", "Dimapur", "Ganeshnagar Dimapur"],
    Kohima: ["Kohima"],
  },

  Manipur: {
    "Imphal West": ["Imphal", "Lamphelpat Industrial Estate"],
    "Imphal East": ["Imphal East", "Takyelpat Industrial Estate"],
  },

  Mizoram: {
    Aizawl: ["Aizawl", "Zuangtui Industrial Estate"],
  },

  "Arunachal Pradesh": {
    "Papum Pare": ["Naharlagun", "Itanagar", "Nirjuli"],
  },

  Sikkim: {
    "East Sikkim": ["Rangpo", "Gangtok", "Singtam"],
    "South Sikkim": ["Namchi", "Jorethang"],
  },
};
