-- ============================================================
-- 061_expense_enhancements.sql
-- Adds expense numbers, automated activity logs, and updates roles
-- ============================================================

-- 1. ADD EXPENSE_SEQ TO ACCOUNT_SEQUENCES
ALTER TABLE account_sequences ADD COLUMN IF NOT EXISTS expense_seq BIGINT DEFAULT 0;

-- 2. ADD EXPENSE_NUMBER TO EXPENSES
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_number TEXT;

-- 3. AUTO-GENERATION OF EXPENSE NUMBER
CREATE OR REPLACE FUNCTION get_next_expense_number(p_account_id UUID)
RETURNS TEXT AS $$
DECLARE
  v_seq BIGINT;
BEGIN
  INSERT INTO account_sequences (account_id, expense_seq)
  VALUES (p_account_id, 1)
  ON CONFLICT (account_id) DO UPDATE
  SET expense_seq = COALESCE(account_sequences.expense_seq, 0) + 1
  RETURNING expense_seq INTO v_seq;
  
  -- Format: EXP-0001
  RETURN 'EXP-' || LPAD(v_seq::text, 4, '0');
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_expense_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.expense_number IS NULL OR NEW.expense_number = '' THEN
    NEW.expense_number := get_next_expense_number(NEW.account_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_expense_number ON expenses;
CREATE TRIGGER trg_set_expense_number
BEFORE INSERT ON expenses
FOR EACH ROW EXECUTE FUNCTION set_expense_number();

-- Backfill expense_number for existing expenses
DO $$
DECLARE
  exp_record RECORD;
BEGIN
  FOR exp_record IN SELECT id, account_id FROM expenses WHERE expense_number IS NULL ORDER BY created_at ASC LOOP
    UPDATE expenses 
    SET expense_number = get_next_expense_number(exp_record.account_id)
    WHERE id = exp_record.id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Make expense_number NOT NULL after backfill
ALTER TABLE expenses ALTER COLUMN expense_number SET NOT NULL;
ALTER TABLE expenses ADD CONSTRAINT expenses_account_id_expense_number_key UNIQUE(account_id, expense_number);

-- 4. AUTO-LOGGING TO MODULE_ACTIVITIES
CREATE OR REPLACE FUNCTION log_expense_activity()
RETURNS TRIGGER AS $$
DECLARE
  v_user_id UUID;
  v_employee_name TEXT;
  v_action TEXT;
  v_message TEXT;
BEGIN
  -- We need the user_id for the log.
  -- On INSERT/UPDATE, we can get the user_id from auth.uid() if it's via API.
  -- Otherwise, we can fallback to the employee_id's user_id.
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    SELECT user_id INTO v_user_id FROM profiles WHERE id = NEW.employee_id;
  END IF;

  SELECT full_name INTO v_employee_name FROM profiles WHERE id = NEW.employee_id;

  IF TG_OP = 'INSERT' THEN
    v_action := 'created';
    v_message := 'Expense ' || NEW.expense_number || ' generated by ' || COALESCE(v_employee_name, 'Unknown');
  ELSIF TG_OP = 'UPDATE' THEN
    -- Check if status changed
    IF OLD.status IS DISTINCT FROM NEW.status THEN
      IF NEW.status = 'Approved' THEN
        v_action := 'approved';
        v_message := 'Expense ' || NEW.expense_number || ' approved';
      ELSIF NEW.status = 'Rejected' THEN
        v_action := 'rejected';
        v_message := 'Expense ' || NEW.expense_number || ' rejected';
      ELSE
        v_action := 'status_changed';
        v_message := 'Expense ' || NEW.expense_number || ' status changed to ' || NEW.status;
      END IF;
    ELSE
      -- Generic edit
      v_action := 'edited';
      v_message := 'Expense ' || NEW.expense_number || ' edited by ' || COALESCE(v_employee_name, 'Unknown');
    END IF;
  END IF;

  INSERT INTO module_activities (
    account_id,
    user_id,
    module_name,
    record_id,
    action,
    message,
    details
  ) VALUES (
    NEW.account_id,
    v_user_id,
    'expense',
    NEW.id,
    v_action,
    v_message,
    '{}'::jsonb
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_log_expense_activity ON expenses;
CREATE TRIGGER trg_log_expense_activity
AFTER INSERT OR UPDATE ON expenses
FOR EACH ROW
EXECUTE FUNCTION log_expense_activity();


-- 5. EMPLOYEE RIGHTS
-- Add expenses to Admin and Field Agent roles
DO $$
DECLARE
  role_record RECORD;
  new_perms JSONB;
BEGIN
  FOR role_record IN SELECT id, name, permissions FROM employee_roles LOOP
    new_perms := role_record.permissions;
    
    IF role_record.name = 'Admin' THEN
      -- Admin might just have {"all": true} but we can explicitly add it just in case
      new_perms := jsonb_set(new_perms, '{expenses}', '{"view": true, "add": true, "edit": true, "delete": true, "approve": true}'::jsonb, true);
    ELSIF role_record.name = 'Field Agent' THEN
      new_perms := jsonb_set(new_perms, '{expenses}', '{"view": true, "add": true, "edit": true, "delete": false, "approve": false, "scope": "own"}'::jsonb, true);
    ELSE
      -- Any other custom roles, give them read-only by default or ignore
      new_perms := jsonb_set(new_perms, '{expenses}', '{"view": true, "add": false, "edit": false, "approve": false}'::jsonb, true);
    END IF;

    UPDATE employee_roles SET permissions = new_perms WHERE id = role_record.id;
  END LOOP;
END;
$$ LANGUAGE plpgsql;
